optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  model_test_run: true
  epoch: 300
  batch_size: 4
  save_model: true
  log_loss: true
  test_step: 1
  reproducible: true
  seed: 2023
  tensorboard: true
  ssl: false
  parameter_path: './datasets/sequential/aug/parameters/param.pkl'

test:
  metrics: [recall, ndcg, precision]
  k: [1, 2, 3]
  batch_size: 4

data:
  type: sequential
  name: aug
  seq_aug: false

model:
  name: cl4srec
  context_encoder: lstm
  dropout_rate: 0.1
  n_layers: 2
  embedding_size: 64
  n_heads: 2
  max_seq_len: 10
  lmd: 0.1
  tau: 1

lstm:
  hidden_size: 64
  num_layers: 30
  output_size: 256

tune:
  enable: false
  hyperparameters: [dropout_rate, lmb, tau]
  dropout_rate: [0.1, 0.3, 0.5]
  lmb: [0.05, 0.1, 0.2]
  tau: [0.5, 0.7, 0.9]
