optimizer:
  name: adam
  lr: 1.0e-3
  final_lr: 1.0e-6
  weight_decay: 0

train:
  model_test_run: false
  test_run_sample_no: 100
  weighted_loss_fn: true
  epoch: 1000
  batch_size: 64
  save_model: true
  log_loss: true
  test_step: 1
  reproducible: true
  seed: 12
  tensorboard: true
  conf_mat: true
  ssl: false
  gradient_accumulation: false
  accumulation_steps: 4

test:
  metrics: [precision, recall, f1score, accuracy]
  k: [1, 2, 3]
  batch_size: 64
  train_eval: false

data:
  type: sequential
  name: fix
  seq_aug: false
  dynamic_context_window_length: 100

model:
  name: cl4srec
  context_encoder: tempcnn
  tcn_num_channels: [80, 50, 25]
  tcn_kernel_size: 3
  interaction_encoder: sasrec
  dropout_rate_trans: 0.3
  dropout_rate_tcn: 0.25
  dropout_rate_fc_tcn: 0.4
  dropout_rate_fc_trans: 0.5
  dropout_rate_fc_concat: 0.3
  dropout_rate_fc_static: 0.1
  n_layers: 2
  embedding_size: 786
  n_heads: 2
  max_seq_len: 10
  lmd: 0.1
  tau: 1
  encoder_combine: concat

lstm:
  hidden_size: 64
  num_layers: 2

tune:
  enable: false
  hyperparameters: [dropout_rate, lmd, tau]
  dropout_rate: [0.1, 0.2, 0.3]
  lmd: [0.05, 0.1, 0.2]
  tau: [0.5, 0.7, 0.9]
