optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 10
  batch_size: 256
  save_model: true
  log_loss: true
  test_step: 1
  reproducible: true
  seed: 2023
  tensorboard: true

test:
  metrics: [recall, ndcg]
  k: [2, 3,5]
  batch_size: 256

data:
  type: sequential
  name: carsii_random_delta
  seq_aug: true

model:
  name: cl4srec
  dropout_rate: 0.1
  n_layers: 2
  embedding_size: 64
  n_heads: 2
  max_seq_len: 120
  lmd: 0.1
  tau: 1

tune:
  enable: false
  hyperparameters: [dropout_rate, lmb, tau]
  dropout_rate: [0.1, 0.3, 0.5]
  lmb: [0.05, 0.1, 0.2]
  tau: [0.5, 0.7, 0.9]
